### ISSUE TITLE
大文件上传下载

### ISSUE THREAD

**Issue by cocosip** [caozhiyuan/FastDFSNetCore#11]
没有对大文件上传做支持吗？昨天测试的时候使用几个大的文件直接就暴内存了。

**Comment by caozhiyuan** [comment]
没有， 主要是几M小文件 ， 大文件你传的字节数组吗？（要新增一个stream上传的接口）  @cocosip 

你把你测试代码发下。

**Comment by caozhiyuan** [comment]
也可以你自己分段上传 每次2M上传然后用UploadAppenderFileAsync接口Append

然后下载大文件也是分段下载 自己处理。

**Comment by cocosip** [comment]
我们还是有挺多文件可能会比较大,所以还是有Stream上传跟Stream下载的需求。
如果是用AppendFile 会对binlog造成很大的压力, Append应该会新增一行数据的。
用的 .net core,找了一圈也没找到很合适的客户端。

**Comment by caozhiyuan** [comment]
@cocosip fixed in
https://github.com/caozhiyuan/FastDFSNetCore/pull/12

sample : 
https://github.com/caozhiyuan/FastDFSNetCore/blob/master/src/FastDFS.Test/Program.cs#L266
https://github.com/caozhiyuan/FastDFSNetCore/blob/master/src/FastDFS.Test/Program.cs#L285

**Comment by caozhiyuan** [comment]
@cocosip  you can use UploadFileAsync(StorageNode storageNode, Stream contentStream, string fileExt)
