### ISSUE TITLE
FDFSConfig 改成外部可配置项

### ISSUE THREAD

**Issue by zhijiezhu** [caozhiyuan/FastDFSNetCore#2]
FDFSConfig 改成外部可配置项比较好

**Comment by caozhiyuan** [comment]
哪个参数需要手动配置？连接池大小？@Myzhuzhijie

**Comment by caozhiyuan** [comment]
你可以提交个PR

**Comment by XiaoLongRenMengXin** [comment]
这个目前可以配置了嘛？连接时间

**Comment by zhijiezhu** [comment]
要动态配置的话，目前这个框架得大改

**Comment by XiaoLongRenMengXin** [comment]
一般来说出现：远程主机强迫关闭了一个现有的连接、你的主机中的软件中止了一个已建立的连接这种错误是请求时间超时了还是网络不稳定呢！

**Comment by caozhiyuan** [comment]
错误堆栈是啥？@XiaoLongRenMengXin 
参考：FastDFS.Test/Program.cs 里面的代码

**Comment by caozhiyuan** [comment]
@Myzhuzhijie  走配置的话，为什么需要大改？

**Comment by zhijiezhu** [comment]
配置写到配置文件里，以依赖注入配置类的方式读取，不得大改？

**Comment by zhijiezhu** [comment]
意思就是把它写成aspnetcore的中间件，现在只不过是个类库，使用上并不友好

**Comment by caozhiyuan** [comment]
弄成单例就行了 启动时候加载下配置 configer下ConnectionManager ，或者把ConnectionManager改成单例（不用静态变量了）

**Comment by zhijiezhu** [comment]
这样也是可以，只是修改了就得重启

**Comment by caozhiyuan** [comment]
有时间我改个core版本的

**Comment by XiaoLongRenMengXin** [comment]
咦,应该是那部分呢？我是按异步的demo来做的,要看平行那部分的代码嘛？

**Comment by XiaoLongRenMengXin** [comment]
对了,博主,groupName在项目中是必填的嘛？默认group1是需要和服务器对应的嘛？

**Comment by caozhiyuan** [comment]
是的 因为可能有多个group, FDFSHelper和program里面代码都可以参考

**Comment by caozhiyuan** [comment]
是的 因为可能有多个group, FDFSHelper和program里面代码都可以参考
