### ISSUE TITLE
Get Response Error, Error Code:52

### ISSUE THREAD

**Issue by XiaoLongRenMengXin** [caozhiyuan/FastDFSNetCore#5]
我在调用`FastDFSClient.GetStorageNodeAsync(GroupName)时产生错误` “Get Response Error, Error Code:52” 根据楼主之前的解释是说无效交换！那么是指无效交换什么呢？

**Comment by caozhiyuan** [comment]
一直都有问题吗？ 还是服务器问题？

**Comment by XiaoLongRenMengXin** [comment]
今天测试一直都有问题,上一个项目使用正常,但是今天也出现了同样的问题

**Comment by XiaoLongRenMengXin** [comment]
和同事交流后得知有一段事件内服务器不太正常,但是随后我测试后服务器22122端口 已经查看服务器图片都是正常的

**Comment by caozhiyuan** [comment]
查看图片走的单独的服务（8888端口） 或者 直接用ng代理到文件夹的 ， Error Code:52 是fastdfs server返回的（server源码里面返回errno地方太多，或者你有时间可以自己研究下https://github.com/happyfish100/fastdfs   你有时间在你们开发环境压测下。

**Comment by XiaoLongRenMengXin** [comment]
嗯呢 好的,那我就把这个关闭了 不是我们插件的问题
